import type { GitClassification, GitChangeStatus, GitStatusEntry } from '../types';

interface RawEntry {
  readonly xy: string;
  readonly path: string;
}

const CLASSIFICATION_RULES: ReadonlyArray<{
  pattern: RegExp;
  classification: GitClassification;
  reason: string;
  patternFn: (path: string) => string;
}> = [
  {
    pattern: /^out\//,
    classification: 'build-artifact',
    reason: 'electron-vite build output — regenerated on every `npm run build`',
    patternFn: () => 'out/',
  },
  {
    pattern: /^dist\//,
    classification: 'build-artifact',
    reason: 'Vite production bundle — regenerated on every `npm run build:web`',
    patternFn: () => 'dist/',
  },
  {
    pattern: /^playwright-report\//,
    classification: 'test-report',
    reason: 'Playwright HTML report — generated by `npm test`',
    patternFn: () => 'playwright-report/',
  },
  {
    pattern: /^test-results\//,
    classification: 'test-report',
    reason: 'Playwright test result artifacts — generated by `npm test`',
    patternFn: () => 'test-results/',
  },
  {
    pattern: /^node_modules\//,
    classification: 'dependency',
    reason: 'npm dependency tree — managed by package-lock.json, never commit',
    patternFn: () => 'node_modules/',
  },
  {
    pattern: /\.(log|log\.\d+)$/,
    classification: 'log',
    reason: 'Runtime log file — ephemeral, safe to ignore',
    patternFn: (p) => `*.${p.split('.').at(-1) ?? 'log'}`,
  },
  {
    pattern: /^(src|electron|public)\//,
    classification: 'source',
    reason: 'Source file — intentional change, should be reviewed and committed',
    patternFn: (p) => p,
  },
  {
    pattern: /^(package\.json|package-lock\.json|tsconfig.*\.json|\.eslintrc.*|eslint\.config\..*)$/,
    classification: 'config',
    reason: 'Project configuration — intentional change, should be committed',
    patternFn: (p) => p,
  },
];

function parseStatus(xy: string): GitChangeStatus {
  const code = xy.trim()[0] ?? '?';
  const map: Record<string, GitChangeStatus> = {
    M: 'modified',
    A: 'added',
    D: 'deleted',
    R: 'renamed',
    '?': 'untracked',
  };
  return map[code] ?? 'modified';
}

export function classifyEntry(entry: RawEntry): GitStatusEntry {
  for (const rule of CLASSIFICATION_RULES) {
    if (rule.pattern.test(entry.path)) {
      const suggestIgnore =
        rule.classification === 'build-artifact' ||
        rule.classification === 'test-report' ||
        rule.classification === 'dependency' ||
        rule.classification === 'log';
      return {
        path: entry.path,
        status: parseStatus(entry.xy),
        classification: rule.classification,
        reason: rule.reason,
        suggestIgnore,
        suggestedPattern: rule.patternFn(entry.path),
      };
    }
  }
  return {
    path: entry.path,
    status: parseStatus(entry.xy),
    classification: 'unknown',
    reason: 'File origin unclear — review before committing or ignoring',
    suggestIgnore: false,
    suggestedPattern: entry.path,
  };
}

export function parseGitPorcelain(output: string): ReadonlyArray<RawEntry> {
  return output
    .split('\n')
    .map((line) => line.trimEnd())
    .filter((line) => line.length >= 3)
    .map((line) => {
      const xy = line.slice(0, 2);
      const rawPath = line.slice(3);
      // Handle renamed files: "R old-path -> new-path" or porcelain v1 "R old\0new"
      // Porcelain v1 format for renames: "R  old-name -> new-name" (with arrow)
      const arrowIdx = rawPath.indexOf(' -> ');
      const pathPart = arrowIdx >= 0 ? rawPath.slice(arrowIdx + 4) : rawPath;
      // Strip surrounding quotes (git uses them for paths with special chars)
      const path = pathPart.replace(/^"(.+)"$/, '$1');
      return { xy, path };
    });
}
