import { test, expect, type Page } from '@playwright/test';

async function expectScreen(page: Page, token: string) {
  await expect(page.locator(`text=${token}`).first()).toBeVisible({ timeout: 5000 });
}

// Full pi mock that satisfies app startup requirements
const fullPiMock = `
  const noop = () => {};
  const noopCleanup = () => () => {};
  window.__piGitStatusOverride = null;
  Object.defineProperty(window, 'pi', {
    value: {
      isElectron: false,
      send: () => Promise.resolve(),
      abort: () => Promise.resolve(),
      onEvent: noopCleanup(),
      getState: () => Promise.resolve({ available: false, running: false, binaryPath: null }),
      fs: {
        readFile: () => Promise.reject(new Error('not available')),
        writeFile: () => Promise.resolve(),
        listDir: () => Promise.resolve([]),
        exists: () => Promise.resolve(false),
      },
      pkg: {
        install: () => Promise.reject(new Error('not available')),
        uninstall: () => Promise.reject(new Error('not available')),
        update: () => Promise.reject(new Error('not available')),
      },
      session: {
        list: () => Promise.resolve([]),
        read: () => Promise.resolve([]),
        rename: () => Promise.resolve(),
        delete: () => Promise.resolve(),
      },
      app: {
        getVersion: () => Promise.resolve('0.0.0'),
        getCwd: () => Promise.resolve('/repo'),
        quit: () => Promise.resolve(),
      },
      git: {
        status: () => window.__piGitStatusOverride
          ? Promise.resolve(window.__piGitStatusOverride)
          : Promise.resolve({ entries: [], cwd: '/repo', gitignorePath: '/repo/.gitignore' }),
        readGitignore: () => Promise.resolve(''),
        appendGitignore: () => Promise.resolve(),
      },
      onNavigate: () => () => {},
      onOverlay: () => () => {},
    },
    configurable: true,
  });
`;

async function navigateToGitStatus(page: Page) {
  await page.goto('/');
  await expectScreen(page, 'pi ui design system');
  await page.locator('text=Git Status').first().click();
  await expectScreen(page, 'Git Status');
}

test.describe('GitStatus screen — no pi API (web mode)', () => {
  test.beforeEach(async ({ page }) => {
    page.on('console', () => {});
    await navigateToGitStatus(page);
  });

  test('renders the Git Status heading', async ({ page }) => {
    await expect(page.locator('text=Git Status').first()).toBeVisible();
  });

  test('renders the Refresh button', async ({ page }) => {
    await expect(page.locator('button', { hasText: 'Refresh' }).first()).toBeVisible();
  });

  test('back button navigates to settings', async ({ page }) => {
    await page.locator('button', { hasText: '← Settings' }).first().click();
    await expectScreen(page, 'Settings');
  });
});

test.describe('GitStatus screen — mocked pi API', () => {
  const buildArtifactEntry = {
    path: 'out/main/index.cjs',
    status: 'untracked',
    classification: 'build-artifact',
    reason: 'electron-vite build output — regenerated on every `npm run build`',
    suggestIgnore: true,
    suggestedPattern: 'out/',
  };

  const sourceEntry = {
    path: 'src/screens/Settings.tsx',
    status: 'modified',
    classification: 'source',
    reason: 'Source file — intentional change, should be reviewed and committed',
    suggestIgnore: false,
    suggestedPattern: 'src/screens/Settings.tsx',
  };

  const testReportEntry = {
    path: 'playwright-report/index.html',
    status: 'modified',
    classification: 'test-report',
    reason: 'Playwright HTML report — generated by `npm test`',
    suggestIgnore: true,
    suggestedPattern: 'playwright-report/',
  };

  test('build artifacts shown in Recommended to gitignore section', async ({ page }) => {
    await page.addInitScript(fullPiMock);
    await page.goto('/');
    await expectScreen(page, 'pi ui design system');
    // Override the git status result before navigating
    await page.evaluate((entry) => {
      (window as unknown as Record<string, unknown>).__piGitStatusOverride = {
        entries: [entry],
        cwd: '/repo',
        gitignorePath: '/repo/.gitignore',
      };
    }, buildArtifactEntry);
    await page.locator('text=Git Status').first().click();
    await expectScreen(page, 'Git Status');
    await expect(page.locator('text=Recommended to gitignore').first()).toBeVisible({ timeout: 5000 });
    await expect(page.locator('text=out/main/index.cjs').first()).toBeVisible();
  });

  test('source files shown in Review before committing section', async ({ page }) => {
    await page.addInitScript(fullPiMock);
    await page.goto('/');
    await expectScreen(page, 'pi ui design system');
    await page.evaluate((entry) => {
      (window as unknown as Record<string, unknown>).__piGitStatusOverride = {
        entries: [entry],
        cwd: '/repo',
        gitignorePath: '/repo/.gitignore',
      };
    }, sourceEntry);
    await page.locator('text=Git Status').first().click();
    await expectScreen(page, 'Git Status');
    await expect(page.locator('text=Review before committing').first()).toBeVisible({ timeout: 5000 });
    await expect(page.locator('text=src/screens/Settings.tsx').first()).toBeVisible();
  });

  test('Queue all button appears when suggestIgnore entries exist', async ({ page }) => {
    await page.addInitScript(fullPiMock);
    await page.goto('/');
    await expectScreen(page, 'pi ui design system');
    await page.evaluate((entries) => {
      (window as unknown as Record<string, unknown>).__piGitStatusOverride = {
        entries,
        cwd: '/repo',
        gitignorePath: '/repo/.gitignore',
      };
    }, [buildArtifactEntry, testReportEntry]);
    await page.locator('text=Git Status').first().click();
    await expectScreen(page, 'Git Status');
    await expect(page.locator('button', { hasText: 'Queue all' }).first()).toBeVisible({ timeout: 5000 });
  });

  test('clean working tree shows Working tree clean message', async ({ page }) => {
    await page.addInitScript(fullPiMock);
    await page.goto('/');
    await expectScreen(page, 'pi ui design system');
    // Leave __piGitStatusOverride as null → returns empty entries
    await page.locator('text=Git Status').first().click();
    await expectScreen(page, 'Git Status');
    await expect(page.locator('text=Working tree clean').first()).toBeVisible({ timeout: 5000 });
  });
});
